[jobs.lab1]
image = { source = "dockerfile", path = "."}

run = [
#  "ls",
#  "ls ..",
  "echo $input",
  "cat $input",
  "cat $input | java -jar ./miniSysY-Compiler-1.0-SNAPSHOT-jar-with-dependencies.jar > $ir",
]
